/************
Gabe Baduqui
CIS276DA
Lesson 3
************/


-- 1Ciii
START TRANSACTION;

UPDATE SCORE SET SCORE = 13 WHERE EVENT_ID = 5 AND STUDENT_ID = 8;

UPDATE SCORE SET SCORE = 18 WHERE EVENT_ID = 5 AND STUDENT_ID = 9;

COMMIT;