-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema VIDEO_STORE_DB
-- -----------------------------------------------------
-- Scheama for CIS276 Video Store Database Final Project

-- -----------------------------------------------------
-- Schema VIDEO_STORE_DB
--
-- Scheama for CIS276 Video Store Database Final Project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VIDEO_STORE_DB` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `VIDEO_STORE_DB` ;

-- -----------------------------------------------------
-- Table `VIDEO_STORE_DB`.`CUSTOMER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VIDEO_STORE_DB`.`CUSTOMER` (
  `CUSTOMER_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ACCOUNT_CREATED_DTTM` DATETIME NOT NULL,
  `ACCOUNT_LAST_LOGIN_DTTM` DATETIME NOT NULL,
  `ACCOUNT_TYPE` VARCHAR(32) NOT NULL,
  `FIRST_NAME` VARCHAR(64) NULL,
  `LAST_NAME` VARCHAR(64) NULL,
  `ADDRESS` VARCHAR(128) NULL,
  `ADDRESS2` VARCHAR(128) NULL,
  `CITY` VARCHAR(64) NULL,
  `STATE` VARCHAR(32) NULL,
  `ZIPCODE` VARCHAR(16) NULL,
  `BIRTHDAY` DATE NULL,
  `PHONE` VARCHAR(32) NULL,
  `ACTIVE_CHECKOUTS` SMALLINT UNSIGNED NOT NULL,
  `OVERDUE_CHECKOUTS` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`CUSTOMER_ID`),
  UNIQUE INDEX `CUSTOMER_ID_UNIQUE` (`CUSTOMER_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VIDEO_STORE_DB`.`VIDEO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VIDEO_STORE_DB`.`VIDEO` (
  `VIDEO_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(128) NULL,
  `SUBTITLE` VARCHAR(128) NULL,
  `RELEASE_YEAR` YEAR NOT NULL,
  `GENRE` VARCHAR(32) NULL,
  `MPAA_RATING` VARCHAR(8) NULL,
  `DIRECTOR` VARCHAR(128) NULL,
  `PRODUCER` VARCHAR(128) NULL,
  `WRITER` VARCHAR(128) NULL,
  `PRODUCING_STUDIO` VARCHAR(128) NULL,
  `LENGTH` TIME NOT NULL,
  `CRITIC_RATING` TINYINT UNSIGNED NULL,
  `LAST_CHECKOUT_OUT_DTTM` DATETIME NOT NULL,
  PRIMARY KEY (`VIDEO_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VIDEO_STORE_DB`.`DATABASE_ROLE_PRIVELEGES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VIDEO_STORE_DB`.`DATABASE_ROLE_PRIVELEGES` (
  `DATABASE_ROLE_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DATABASE_ROLE_NAME` VARCHAR(64) NOT NULL,
  `PRIVILEGE` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`DATABASE_ROLE_ID`),
  UNIQUE INDEX `DATABASE_ROLE_ID_UNIQUE` (`DATABASE_ROLE_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VIDEO_STORE_DB`.`EMPLOYEE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VIDEO_STORE_DB`.`EMPLOYEE` (
  `EMPLOYEE_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `JOBCODE` INT UNSIGNED NULL,
  `JOB_TITLE` VARCHAR(128) NULL,
  `JOB_LEVEL` VARCHAR(32) NULL,
  `JOB_FAMILY` VARCHAR(64) NULL,
  `FLSA_STATUS` VARCHAR(16) NULL,
  `PAY_RATE` DECIMAL(10,2) NULL,
  `PAY_FREQUENCY` VARCHAR(32) NULL,
  `STORE_ID` INT UNSIGNED NULL,
  `EMPLOYMENT_BEGIN_DATE` DATE NOT NULL,
  `EMPLOYMENT_END_DATE` DATE NULL,
  `DATABASE_ROLE` INT UNSIGNED NULL,
  PRIMARY KEY (`EMPLOYEE_ID`),
  INDEX `FK_EMPLOYEE_DATABASEROLE_idx` (`DATABASE_ROLE` ASC) VISIBLE,
  CONSTRAINT `FK_EMPLOYEE_DATABASEROLE`
    FOREIGN KEY (`DATABASE_ROLE`)
    REFERENCES `VIDEO_STORE_DB`.`DATABASE_ROLE_PRIVELEGES` (`DATABASE_ROLE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VIDEO_STORE_DB`.`CHECKOUT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VIDEO_STORE_DB`.`CHECKOUT` (
  `CHECKOUT_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` INT UNSIGNED NOT NULL,
  `VIDEO_ID` INT UNSIGNED NOT NULL,
  `EMPLOYEE_ID` INT UNSIGNED NOT NULL,
  `CHECKOUT_DATE` DATE NOT NULL,
  `DUE_DATE` DATE NULL,
  `DATE_RETURNED` DATE NULL,
  `CHECKOUT_FEE` DECIMAL(6,2) NOT NULL,
  `LATE_FEE` DECIMAL(6,2) NULL,
  PRIMARY KEY (`CHECKOUT_ID`),
  UNIQUE INDEX `CHECKOUT_ID_UNIQUE` (`CHECKOUT_ID` ASC) VISIBLE,
  INDEX `FK_CHECKOUT_CUSTOMERID_idx` (`CUSTOMER_ID` ASC) VISIBLE,
  INDEX `FK_CHECKOUT_VIDEOID_idx` (`VIDEO_ID` ASC) VISIBLE,
  INDEX `FK_CHECKOUT_EMPLOYEEID_idx` (`EMPLOYEE_ID` ASC) VISIBLE,
  CONSTRAINT `FK_CHECKOUT_CUSTOMERID`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `VIDEO_STORE_DB`.`CUSTOMER` (`CUSTOMER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CHECKOUT_VIDEOID`
    FOREIGN KEY (`VIDEO_ID`)
    REFERENCES `VIDEO_STORE_DB`.`VIDEO` (`VIDEO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CHECKOUT_EMPLOYEEID`
    FOREIGN KEY (`EMPLOYEE_ID`)
    REFERENCES `VIDEO_STORE_DB`.`EMPLOYEE` (`EMPLOYEE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
